name: boreholes-prod
channels:
  - conda-forge
dependencies:
  - python==3.10
  - boto3
  - pandas
  - levenshtein
  - pathlib==1.0.1
  - python-dotenv==1.0.1
  - scikit-learn==1.4.0
  - click==8.1.7
  - PyYAML==6.0.1
  - langdetect==1.0.9
  - pip
  - pip:
      - amazon-textract-textractor
      - backoff
      - PyMuPDF==1.23.26
      - opencv-python-headless
      - quads==1.1.0
      - -e .
