[project]
name = "swisstopo-boreholes"
version = "0.0.1-dev"
description = "Python project to analyse borehole profiles."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.ruff]
line-length = 119

[tool.ruff.lint.pydocstyle]
convention = "google"