[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "swisstopo-boreholes"
version = "0.0.1-dev"
description = "Python project to analyse borehole profiles."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3",
    "pandas",
    "levenshtein",
    "pathlib==1.0.1",
    "python-dotenv==1.0.1",
    "scikit-learn==1.4.0",
    "click==8.1.7",
    "PyYAML==6.0.1",
    "langdetect==1.0.9",
    "backoff",
    "PyMuPDF==1.23.26",
    "opencv-python-headless",
]

[project.scripts]
boreholes-extract-layers = "stratigraphy.main:start_pipeline"
boreholes-download-profiles = "stratigraphy.get_files:download_directory_froms3"

[tool.ruff.lint]
select = [
    # pydocstyle
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    "D102",  # Missing docstring in a public method
    "D105",  # Missing docstring in magic method
    "D107",  # Missing docstring in `__init__`
    ]

[tool.ruff]
line-length = 119

[tool.ruff.lint.pydocstyle]
convention = "google"