name: pipeline_run

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pipeline_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Environment and run pipeline
      shell: bash
      run: |
        wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        bash Miniforge3.sh -b -p "${HOME}/conda"
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda init --all
        source "${HOME}/.bash_profile"
        conda env create -f environment-prod.yml
        conda activate boreholes-prod
        echo "Running pipeline"
        boreholes-extract-layers -l -i example/example_borehole_profile.pdf -o example/ -p example/predictions.json