name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Environment and run tests
      shell: bash
      run: |
        wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        bash Miniforge3.sh -b -p "${HOME}/conda"
        source "${HOME}/conda/etc/profile.d/conda.sh"
        conda init --all
        source "${HOME}/.bash_profile"
        conda env create -f environment-dev.yml
        conda activate boreholes-dev
        pytest